---
- name: Create global output directory if it does not exist
  ansible.builtin.file:
    path: ../output/{{ b2bi_namespace }}
    state: directory
    mode: '0755'

- name: Template the DB2 Namespace for reuse
  ansible.builtin.template:
    src: templates/b2bi-namespace.yml.j2
    dest: ../output/{{ b2bi_namespace }}/{{ b2bi_namespace }}-namespace.yml
    mode: '0644'

- name: Create B2Bi namespace
  kubernetes.core.k8s:
    state: present
    src: ../output/{{ b2bi_namespace }}/{{ b2bi_namespace }}-namespace.yml

- name: Create registry secret content "{{ b2bi_registry_secret }}"
  no_log: true
  vars:
    auth: "{{ registry_user }}:{{ registry_key }}"
    auth_b64: "{{ auth | b64encode }}"
    content:
      - '{"auths":{"{{ registry }}":{"username":"{{ registry_user }}","password":"{{ registry_key }}",'
      - '"email":"{{ registry_user }}","auth":"{{ auth_b64 }}"}'
      - "}"
      - "}"
  ansible.builtin.set_fact:
    new_secret: "{{ content | join('') }}"

- name: Generate b2bi registry secret "{{ b2bi_registry_secret }}"
  no_log: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: "{{ b2bi_registry_secret }}"
        namespace: "{{ b2bi_namespace }}"
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"

- name: "Generate secret '{{ b2bi_system_passphrase_secret }}'"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ b2bi_system_passphrase_secret }}"
        namespace: "{{ b2bi_namespace }}"
      data:
        SYSTEM_PASSPHRASE: "{{ b2bi_system_passphrase | b64encode }}"

- name: "Generate secret '{{ b2bi_liberty_keystore_password_secret }}'"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ b2bi_liberty_keystore_password_secret }}"
        namespace: "{{ b2bi_namespace }}"
      data:
        SYSTEM_PASSPHRASE: "{{ b2bi_liberty_keystore_password | b64encode }}"
