---
db_values:
  STMT_CONC: "LITERALS"
  SELF_TUNING_MEM: "ON"
  LOCKLIST: "AUTOMATIC"
  MAXLOCKS: "AUTOMATIC"
  PCKCACHESZ: "AUTOMATIC"
  SHEAPTHRES_SHR: "AUTOMATIC"
  SORTHEAP: "AUTOMATIC"
  NUM_IOCLEANERS: "AUTOMATIC"
  NUM_IOSERVERS: "AUTOMATIC"
  DFT_PREFETCH_SZ: "AUTOMATIC"
  MAXAPPLS: "AUTOMATIC"
  APPLHEAPSZ: "AUTOMATIC"
  APPL_MEMORY: "AUTOMATIC"
  DBHEAP: "AUTOMATIC"
  LOGFILSIZ: "65536"
  LOGPRIMARY: "40"
  LOGSECOND: "12"
  NUM_LOG_SPAN: "40"
  DFT_DEGREE: "1"
  LOGBUFSZ: "2152"
  STMTHEAP: "51200 AUTOMATIC"
  CATALOGCACHE_SZ: "300"
  UTIL_HEAP_SZ: "AUTOMATIC"
  CHNGPGS_THRESH: "80"

dbm_values:
  SVCENAME: "50000"
