---
- name: "Configure Sterling Secure Proxy Configuration Manager Namespace"
  ansible.builtin.include_tasks: 01_configure_namespace.yml

- name: "Deploy the SSP CM helm chart configuration"
  ansible.builtin.include_tasks: 02_deploy_ssp_cm.yml
