---
- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Install IBM Operator Catalog Source
  ansible.builtin.include_tasks: 02_install_catalog_source.yml
