---
- name: Check for required environment variables
  ansible.builtin.assert:
    that:
      - entitlement_key != ""
    fail_msg: "Registry key or password is required in order to authenticate against the provided registry"
