---
- name: Create registry secret content "{{ mq_registry_secret }}"
  no_log: true
  vars:
    auth: "{{ registry_user }}:{{ registry_key }}"
    auth_b64: "{{ auth | b64encode }}"
    content:
      - '{"auths":{"{{ registry }}":{"username":"{{ registry_user }}","password":"{{ registry_key }}",'
      - '"email":"{{ registry_user }}","auth":"{{ auth_b64 }}"}'
      - "}"
      - "}"
  ansible.builtin.set_fact:
    mq_new_secret: "{{ content | join('') }}"

- name: Template MQ registry secret for reuse
  ansible.builtin.template:
    src: templates/mq-registry-secret.yml.j2
    dest: ../output/{{ mq_namespace }}/{{ mq_namespace }}-mq-registry-secret.yml
    mode: '0644'

- name: Generate mq registry secret "{{ mq_registry_secret }}"
  no_log: true
  kubernetes.core.k8s:
    state: present
    src: ../output/{{ mq_namespace }}/{{ mq_namespace }}-mq-registry-secret.yml

- name: Template the mq secret for reuse
  ansible.builtin.template:
    src: templates/mq-secret.yml.j2
    dest: ../output/{{ mq_namespace }}/{{ mq_namespace }}-{{ mq_secret }}.yml
    mode: '0644'

- name: Generate mq secret "{{ mq_secret }}"
  kubernetes.core.k8s:
    state: present
    src: ../output/{{ mq_namespace }}/{{ mq_namespace }}-{{ mq_secret }}.yml
