- name: Template the QueueManager instance for reuse
  ansible.builtin.template:
    src: templates/mqinstance.yml.j2
    dest: ../output/{{ mq_namespace }}/{{ mq_namespace }}-{{ mq_crd_name }}-cr-instance.yml
    mode: '0644'

- name: Deploy MQ
  kubernetes.core.k8s:
    state: present
    src: ../output/{{ mq_namespace }}/{{ mq_namespace }}-{{ mq_crd_name }}-cr-instance.yml

- name: Wait for QueueManager instance to start
  ansible.builtin.pause:
    seconds: 30

- name: Wait for the MQ deployment to finish before moving on
  kubernetes.core.k8s_info:
    api_version: mq.ibm.com/v1beta1
    kind: QueueManager
    namespace: "{{ mq_namespace }}"
    name: "{{ mq_crd_name }}"
  register: result
  until: result.resources[0].status.phase == "Running"
  retries: 40
  delay: 30
