---
# B2Bi Settings
b2bi_version: "{{ lookup('env', 'B2BI_VERSION') | default('6.2.0.2', true) }}"
b2bi_license_type: "{{ lookup('env', 'B2BI_LICENSE_TYPE') | default('non-prod', true) }}"

b2bi_app_logs_size: "{{ lookup('env', 'B2BI_APPLOG_SIZE') | default('1Gi', true) }}"

b2bi_app_documents_enabled: "{{ lookup('env', 'B2BI_APPDOC_ENABLED') | default('false', true) }}"
b2bi_app_documents_size: "{{ lookup('env', 'B2BI_APPDOC_SIZE') | default('1Gi', true) }}"

b2bi_namespace: "{{ lookup('env', 'B2BI_NAMESPACE') | default('b2bi', true) }}"
b2bi_serviceaccount: "{{ lookup('env', 'B2BI_SA') | default('b2bi-sa', true) }}"

b2bi_registry_secret: "{{ lookup('env', 'REGISTRY') | default('ibm-registry-secret', true) }}"
b2bi_registry: "{{ lookup('env', 'REGISTRY') | default('cp.icr.io', true) }}"
b2bi_registry_user: "{{ lookup('env', 'REGISTRY_USER') | default('cp', true) }}"
b2bi_registry_key: "{{ lookup('env', 'REGISTRY_KEY') }}"

b2bi_system_passphrase_secret: "{{ lookup('env', 'B2BI_SYSTEM_PASSPHRASE_SECRET') | default('b2bi-system-passphrase-secret', true) }}"
b2bi_system_passphrase: "{{ lookup('env', 'B2BI_SYSTEM_PASSPHRASE') | default('passw0rd', true) }}"

b2bi_liberty_keystore_password_secret: "{{ lookup('env', 'B2BI_LIBERTY_KEYSTORE_PASSWORD_SECRET') | default('b2bi-liberty-secret', true) }}"
b2bi_liberty_keystore_password: "{{ lookup('env', 'B2BI_LIBERTY_KEYSTORE_PASSWORD') | default('changeit', true) }}"

# Registry Settings
registry: "{{ lookup('env', 'REGISTRY') | default('cp.icr.io', true) }}"
registry_user: "{{ lookup('env', 'REGISTRY_USER') | default('cp', true) }}"
registry_key: "{{ lookup('env', 'REGISTRY_KEY') }}"

# DB2 Settings
deploy_db2: "{{ lookup('env', 'B2BI_DEPLOY_DB2') | default(true, true) }}"

db2_version: "{{ lookup('env', 'DB2_VERSION') | default('s11.5.9.0-cn3', true) }}.yml"

db2_namespace: "{{ lookup('env', 'B2BI_DB2_NAMESPACE') | default('b2bi-db2', true) }}"
db2_registry_secret: "{{ lookup('env', 'REGISTRY') | default('ibm-registry-secret', true) }}"
db2_secret: "{{ lookup('env', 'B2BI_DB2_SECRET') | default('db2-secret', true) }}"
db2_service_account: "{{ lookup('env', 'B2BI_DB2_SA') | default('db2-sa', true) }}"

db2_crd_name: "{{ lookup('env', 'B2BI_DB2_CRD_NAME') | default('b2bi-db2', true) }}"
db2_username: "{{ lookup('env', 'B2BI_DB2_USERNAME') | default('db2inst1', true) }}"
db2_password: "{{ lookup('env', 'B2BI_DB2_PASSWORD') | default('passw0rd', true) }}"
db2_dbname: "{{ lookup('env', 'B2BI_DB2_DBNAME') | default('BLUDB', true) }}"
db2_storage_size: "{{ lookup('env', 'B2BI_DB2_SIZE') | default('100Gi', true) }}"

# MQ Settings
deploy_mq: "{{ lookup('env', 'B2BI_DEPLOY_MQ') | default(true, true) }}"

mq_version: "{{ lookup('env', 'MQ_VERSION') | default('v3.4', true) }}.yml"

mq_namespace: "{{ lookup('env', 'MQ_NAMESPACE') | default('b2bi-mq', true) }}"

mq_registry_secret: "{{ lookup('env', 'REGISTRY') | default('ibm-registry-secret', true) }}"

mq_secret: "{{ lookup('env', 'MQ_SECRET') | default('b2bi-mq-secret', true) }}"
mq_admin_password: "{{ lookup('env', 'MQ_ADMIN_PASSWORD') | default('Passw0rd!', true) }}"

mq_crd_name: "{{ lookup('env', 'MQ_CRD_NAME') | default('b2bi-mq', true) }}"

mq_storage_size: "{{ lookup('env', 'MQ_SIZE') | default('20Gi', true) }}"

# JMS Queue Settings
jms_secret: "{{ lookup('env', 'JMS_SECRET') | default('b2bi-jms-queue', true) }}"

jms_user: "admin"
jms_vendor: "IBMMQ"
jms_connection_factory: "com.ibm.mq.jms.MQQueueConnectionFactory"
jms_queue_name: "DEV.QUEUE.1"
jms_channel: "DEV.APP.SVRCONN"
jms_enable_ssl: "false"
