---
deploy_ibm_catalog_source: true
deploy_b2bi: true

registry: cp.icr.io
registry_user: cp
registry_key: ""

file_storage_class: ocs-external-storagecluster-cephfs
block_storage_class: ocs-external-storagecluster-ceph-rbd
