---
b2bi_helm_release_name: auto
b2bi_version: 6.2.0.3
b2bi_license_type: non-prod

b2bi_namespace: b2bi
b2bi_serviceaccount: b2bi-sa

b2bi_registry_secret: ibm-registry-secret
b2bi_registry: cp.icr.io
b2bi_registry_user: cp
b2bi_registry_key:

jms_secret: jms-queue
jms_keystore_path: ""
jms_keystore_secret: ""
jms_truststore_path: ""
jms_truststore_secret: ""
jms_protocol: TLSv1.2

jms_user: appuser
jms_vendor: IBMMQ
jms_connection_factory: com.ibm.mq.jms.MQQueueConnectionFactory
jms_queue_name: DEV.QUEUE.1
jms_channel: DEV.CHANNEL.SVRCONN
jms_enable_ssl: false

b2bi_app_logs_size: 1Gi

b2bi_app_documents_enabled: false
b2bi_app_documents_size: 1Gi

b2bi_data_setup_enabled: true
b2bi_data_setup_upgrade: false

b2bi_seas_enabled: false
b2bi_itx_enabled: false
b2bi_itxa_enabled: false
b2bi_sfg_enabled: false
b2bi_ebics_enabled: false
b2bi_financial_services_enabled: false
b2bi_file_operation_enabled: false
b2bi_fips_enabled: false

b2bi_db_vendor: DB2
b2bi_db_drivers: db2jcc4.jar
b2bi_db_create_schema: true
b2bi_use_oracle_service_name: false
b2bi_cfg_use_ssl: false
b2bi_db_secret: b2bi-db-secret
b2bi_db_truststore: ""
b2bi_db_truststore_secret: ""
b2bi_db_keystore: ""
b2bi_db_keystore_secret: ""
b2bi_admin_email: admin@temp.net
b2bi_smtp_host: localhost
b2bi_document_service_enabled: false

b2bi_system_passphrase_secret: b2bi-system-passphrase-secret
b2bi_system_passphrase: passw0rd

b2bi_liberty_keystore_password_secret: b2bi-liberty-secret
b2bi_liberty_keystore_password: changeit

# accepts on or off
b2bi_nist_enabled: "off"

versions:
  6.2.0.3:
    helm_chart_version: 3.0.5
    ocp_min_version: 4.14
    k8s_min_version: 1.27
    k8s_max_version: 1.29
    resourcesInit_version: 6.2.0.3
    dataSetup_version: 6.2.0.3
    seas_version: 1.0
    itx_version: 10.1.2.0.20231130
    itxa_version: 10.0.1.9-x86_64
    itxa_resourcesInit_version: 10.0.1.9-x86_64
    test_version: 1.1.66
    purge_version: 6.2.0.3
    documentService_version: 1.0.0.3
