---
- name: Check for required environment variables
  ansible.builtin.assert:
    that:
      - registry_key != ""
    fail_msg: "Registry key or password is required in order to authenticate against the provided registry"

- name: Verify that db2_dbname is not over 8 characters
  ansible.builtin.assert:
    that:
      - db2_dbname | length <= 8
    fail_msg: "db2_db2name must be 8 characters or less"
