---
- name: Collect DB2 Version
  ansible.builtin.include_vars: "{{ db2_version }}.yml"

- name: Check for required environment variables
  ansible.builtin.include_tasks: 01_check_vars.yml

- name: Install DB2 Operator
  ansible.builtin.include_tasks: 02_install_db2_operator.yml

- name: Configure the DB2 Namespace
  ansible.builtin.include_tasks: 03_configure_namespace.yml

- name: Deploy DB2
  ansible.builtin.include_tasks: 04_deploy_db2.yml
