- name: Deploy IBM Sterling B2B Integrator on Red Hat Openshift
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../vars/storage.yml
    - ../vars/b2bi-settings.yml
  roles:
    - check_prereqs
    - create_output_directories
    - ibm_catalog_source_deploy
    - b2bi_deploy
